# Generated by Django 3.2 on 2023-03-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
