# Generated by Django 3.1.8 on 2023-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20230315_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
