# Generated by Django 3.1.8 on 2023-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20230723_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ans',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=24),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], default='Physics', max_length=24),
        ),
    ]
