# Generated by Django 3.1.8 on 2023-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20230723_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('cust_add', models.CharField(max_length=255)),
                ('cust_place', models.CharField(max_length=255)),
                ('cust_gstin', models.CharField(max_length=255)),
                ('invoice_num', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
    ]
