# Generated by Django 3.1.8 on 2023-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20230724_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_num',
            field=models.IntegerField(unique=True),
        ),
    ]
