# Generated by Django 3.1.8 on 2023-08-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_invoiceitem_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('transfer', models.PositiveIntegerField()),
            ],
        ),
    ]
