# Generated by Django 3.1.8 on 2023-08-31 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.product'),
            preserve_default=False,
        ),
    ]
