# Generated by Django 3.1.8 on 2023-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='transfer',
            field=models.IntegerField(),
        ),
    ]
